name = "Escape form CSU"
author = "csuers"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1abc34b520617059961a4895f11c306c37156741cb9b8d0ccba1f38c9243367"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
