name = "Escape form CSU"
author = "csuers"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "850eefcc6b8b0d541c1c38688df9b3522b5b716c18ac94ee4bc6c981bae6f646"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
