#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=back;size=5;add_cosmetic=true", "id=belt;size=5;add_cosmetic=true", "id=body;size=5;add_cosmetic=true", "id=bracelet;size=5;add_cosmetic=true", "id=charm;size=5;add_cosmetic=true", "id=head;size=5;add_cosmetic=true", "id=hands;size=5;add_cosmetic=true", "id=ring;size=5;add_cosmetic=true", "id=necklace;size=5;add_cosmetic=true"]

